version: '3'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

  app:
    build: .
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    command: ./bin/dev
    stdin_open: true
    tty: true
    depends_on:
      - db
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mail_data:/tmp

volumes:
  db:
  bundle:
  node_modules:
  mail_data:
